daemon off;
worker_processes 1;
error_log logs/error.log warn;
pid nginx.pid;

events {
    worker_connections 4096;
}

http {
    access_log off;
    server {
        listen 127.0.0.1:18081;

        location / {
            default_type text/plain;
            add_header X-Upstream nginx always;
            return 200 "response from nginx\n";
        }
    }
}

